In [1]:
def sumOfAll(listOfNumbers):
    result = 0
    for number in listOfNumbers:
        result = result + number
    print(result)

In [2]:
sumOfAll([5,8,2,4,7,9])

35


In [3]:
def productOfAll(listOfNumbers):
    result = 1
    for number in listOfNumbers:
        result = result * number
    print(result)

In [4]:
productOfAll([4,3,5,6,2])

720


In [6]:
import numpy as np
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


In [7]:
print('Sorting flattened array')
np.sort(array_hw, axis=None)

Sorting flattened array


array([1, 2, 3, 3, 4, 4, 5, 5, 5, 5, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9,
       9, 9])

In [8]:
print('Sort second column')
np.sort(array_hw, axis=1)

Sort second column


array([[5, 5, 8, 8, 8, 9],
       [3, 5, 5, 7, 7, 7],
       [2, 4, 6, 7, 8, 8],
       [1, 3, 4, 7, 9, 9]])

In [10]:
print('Extract second row onwards')
print(array_hw[1:,...])

Extract second row onwards
[[7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


In [11]:
print('Extract the third column onwards')
print(array_hw[...,2:])

Extract the third column onwards
[[8 8 9 8]
 [5 3 5 7]
 [8 4 2 6]
 [7 3 1 4]]


In [12]:
print('Obtain the square of array_hw')
np.square(array_hw)

Obtain the square of array_hw


array([[25, 25, 64, 64, 81, 64],
       [49, 49, 25,  9, 25, 49],
       [64, 49, 64, 16,  4, 36],
       [81, 81, 49,  9,  1, 16]])

In [13]:
print('Slice the element from the third row and fourth column position 3X4')
print(array_hw[2,3])

Slice the element from the third row and fourth column position 3X4
4


In [14]:
print('Obtain the total sum of array_hw')
array_hw.sum()

Obtain the total sum of array_hw


145

In [15]:
print('How many dimentions does array_hw have?')
array_hw.ndim

How many dimentions does array_hw have?


2

In [18]:
print('What is the data type listed in array_hw?')
array_hw.dtype

What is the data type listed in array_hw?


dtype('int64')

In [19]:
print('What is the size of the memory in bytes consumed by all the elements in array_hw?')
array_hw.nbytes

What is the size of the memory in bytes consumed by all the elements in array_hw?


192